import type { Metadata } from 'next';
import './globals.css';
import { lusitana, montserrat } from '@/app/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className={` ${lusitana.className} antialiased`}>{children}</body>
    </html>
  );
}
